### ISSUE TITLE
# invalid in @base ?

### ISSUE THREAD

**Issue by bdecarne** [IDLabResearch/TurtleValidator#5]
Hi !

https://github.com/IDLabResearch/TurtleValidator/blob/6ef022c8f8ba6e1434186178c4574bc579b1fd6e/public/js/ttl.js#L6209-L6210

Just a question : why # caracter is invalid into @base ?

Thx !
Blaise

**Comment by RubenVerborgh** [comment]
Hi @bdecarne, `@base` identifies the URL of the document; fragment identifiers are not document identifiers.

**Comment by mielvds** [comment]
More info here: https://www.w3.org/TR/turtle/#sec-iri-references
Not sure it is illegal, but more discouraged.

**Comment by RubenVerborgh** [comment]
Actually, I did change my mind on this at some point in N3.js: https://github.com/RubenVerborgh/N3.js/blob/v0.11.2/lib/N3Parser.js#L69-L72

So they should be allowed. I propose to change this in this validator as well.

**Comment by mielvds** [comment]
Strange it is even in there, as this relied on N3.js

**Comment by mielvds** [comment]
Ah I see now, the ttl.js needs to be recompiled. It shouldn't be in this repo, only compiled with yarn or npm. @pietercolpaert ?

**Comment by pietercolpaert** [comment]
![screenshot from 2018-02-16 11-17-30](https://user-images.githubusercontent.com/347073/36303066-0e9714ac-130b-11e8-9179-a18684c3ed6f.png)

Updated N3.js and put new version online - https://github.com/IDLabResearch/TurtleValidator/commit/35885650385e02926badb9860f74f395fb9d1e0d
