### ISSUE TITLE
How do I cite this tool?

### ISSUE THREAD

**Issue by marvinm2** [IDLabResearch/TurtleValidator#8]
Hi, I used your tool for my project to validate my .ttl file, which will be part of a publication. How can I cite this work, this project? I see you have a clear license, but it might be useful to add a DOI to your GitHub page. Are you planning to publish on this project?

**Comment by pietercolpaert** [comment]
Hi @marvinm2 - this project is a small wrapper around N3.js. You can cite this project from that repo: https://github.com/rdfjs/N3.js/ with this doi: https://zenodo.org/badge/latestdoi/3058202
